# Generated by Django 3.2.11 on 2022-06-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20220613_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
