# Generated by Django 3.2.11 on 2022-06-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_images',
            field=models.ImageField(blank='True', null='True', upload_to='images/profile'),
            preserve_default='True',
        ),
    ]
