# Generated by Django 3.2.11 on 2022-06-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_profile_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank='True', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank='True', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank='True', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
