# Generated by Django 3.2.11 on 2022-06-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0021_auto_20220620_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank='True', max_length=255, null=True),
        ),
    ]
